version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=blog_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data:
